export const links = [
    { id: 1, linkName: "What We do", linkUrl: "/" },
    { id: 2, linkName: "Our Team", linkUrl: "/" },
    { id: 3, linkName: "Meet The Crew", linkUrl: "/" },
    { id: 4, linkName: "Team Member", linkUrl: "/" },
    { id: 5, linkName: "Our Services", linkUrl: "/" },
    { id: 6, linkName: "Pricing Plans", linkUrl: "/" },
    { id: 7, linkName: "Payment", linkUrl: "/" },
    { id: 8, linkName: "Testimonials", linkUrl: "/" },
    { id: 9, linkName: "Gift Cards", linkUrl: "/" },
    { id: 10, linkName: "Terms & Conditions", linkUrl: "/" },
    { id: 11, linkName: "Contact Us", linkUrl: "/" },
    { id: 12, linkName: "Leave Us A Note", linkUrl: "/" },
    { id: 13, linkName: "FAQ", linkUrl: "/" },
]